name: Publish Release

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Download packaged distributions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          mkdir dist
          gh release download "$GITHUB_REF_NAME" \
            -D dist \
            -p '*.whl' \
            -p '*.tar.gz'

      - name: Download attestations
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          gh release download "$GITHUB_REF_NAME" \
            -D . \
            -p '*.attestation.json'

      - name: Generate PEP 740 attestation for sdist
        run: uv run jack1142-attestation-testing sdist.attestation.json dist/*.tar.gz

      - name: Generate PEP 740 attestation for wheel
        run: uv run jack1142-attestation-testing wheel.attestation.json dist/*.whl

      - name: Publish
        run: uv publish --index testpypi
